name: 'Auto PR'
description: 'Automatically create a PR'
inputs:
  HEAD_BRANCH:
    description: 'Head branch for the PR'
    required: true
  BASE_BRANCH:
    description: 'Base branch for the PR'
    required: true
  PR_TITLE:
    description: 'Title for the PR'
    required: true
  PR_BODY:
    description: 'Body for the PR'
    required: false
    default: ''
  PR_LABEL:
    description: 'Labels for the PR'
    required: false
    default: ''
  PR_TOKEN:
    description: 'GitHub token'
    required: true
outputs:
  PR_URL:
    description: 'URL of the created PR'
    value: ${{ steps.create_pr.outputs.PR_URL }}
  PR_NUMBER:
    description: 'Number of the created PR'
    value: ${{ steps.create_pr.outputs.PR_NUMBER }}
  PR_HEAD_SHA:
    description: 'SHA of the head commit of the created PR'
    value: ${{ steps.create_pr.outputs.PR_HEAD_SHA }}
runs:
  using: "composite"
  steps:
  - name: Create PR
    id: create_pr
    run: |
      # Create the pull request
      response=$(curl -X POST \
        -H "Authorization: token ${{ inputs.PR_TOKEN }}" \
        -d "{
          \"title\": \"${{ inputs.PR_TITLE }}\",
          \"body\": \"${{ inputs.PR_BODY }}\",
          \"head\": \"${{ inputs.HEAD_BRANCH }}\",
          \"base\": \"${{ inputs.BASE_BRANCH }}\"
        }" \
        "https://api.github.com/repos/${{ github.repository }}/pulls")

      if [[ $response != *"html_url"* ]]; then
        echo "Pull request could not be created. Attention required!" | tee $GITHUB_STEP_SUMMARY
        exit 1
      else
        echo "Pull request created successfully" | tee $GITHUB_STEP_SUMMARY
      fi

      pull_request_number=$(echo "$response" | jq -r '.number')
      echo "PR_NUMBER=${pull_request_number}" >> $GITHUB_OUTPUT

      # Add label to the PR
      labels_response=$(curl -X POST \
      -H "Authorization: token ${{ inputs.PR_TOKEN }}" \
      -d '["'"${{ inputs.PR_LABEL }}"'"]' \
      "https://api.github.com/repos/${{ github.repository }}/issues/$pull_request_number/labels")

      pull_request_head_sha=$(echo "$response" | jq -r '.head.sha')
      echo "PR_HEAD_SHA=${pull_request_head_sha}" >> $GITHUB_OUTPUT

      pr_url=$(echo "$response" | jq -r '.html_url')
      echo "PR_URL=${pr_url}" >> $GITHUB_OUTPUT

    shell: bash # Specify the shell for running commands
